### ISSUE TITLE
VDI Snapshot export broken

### ISSUE THREAD

**Issue by mhoffmann75** [rposudnevskiy/RBDSR#11]
It seems VDI export (e.g. via XenCenter: Create Snapshot, Chose export to file or via API) is broken:

> Aug  9 14:31:45 pns-xen07 SM: [29979] vdi_activate {'sr_uuid': 'ff12160f-ff09-40bb-a874-1366ad907f44', 'subtask_of': 'DummyRef:|257d0fe7-815c-b642-d3fe-2933c542939f|VDI.activate', 'vdi_ref': 'OpaqueRef:b33e90a3-6bed-cb06-52af-5dde1f8a5b0f', 'vdi_on_boot': 'persist', 'args': ['false'], 'vdi_location': '4ad1754e-701f-4403-8e03-a04ce33f83c3', 'host_ref': 'OpaqueRef:0e9c18cb-c243-2d9e-b4db-7bb854e066df', 'session_ref': 'OpaqueRef:90500cdf-1117-dafc-2520-8ecc4af1a7f5', 'device_config': {'SRmaster': 'true'}, 'command': 'vdi_activate', 'vdi_allow_caching': 'false', 'sr_ref': 'OpaqueRef:eab55273-a6e8-6963-3264-7f2df1efd9f5', 'vdi_uuid': '4ad1754e-701f-4403-8e03-a04ce33f83c3'}
> Aug  9 14:31:45 pns-xen07 SM: [29979] lock: opening lock file /var/lock/sm/4ad1754e-701f-4403-8e03-a04ce33f83c3/vdi
> Aug  9 14:31:45 pns-xen07 SM: [29979] blktap2.activate
> Aug  9 14:31:45 pns-xen07 SM: [29979] lock: acquired /var/lock/sm/4ad1754e-701f-4403-8e03-a04ce33f83c3/vdi
> Aug  9 14:31:45 pns-xen07 SM: [29979] Adding tag to: 4ad1754e-701f-4403-8e03-a04ce33f83c3
> Aug  9 14:31:45 pns-xen07 SM: [29979] Activate lock succeeded
> Aug  9 14:31:45 pns-xen07 SM: [29979] ['ceph', 'df', '--format', 'json', '--name', 'client.admin']
> Aug  9 14:31:45 pns-xen07 SM: [29979]   preit SUCCESS
> Aug  9 14:31:45 pns-xen07 SM: [29979] RBDVDI.attach for 4ad1754e-701f-4403-8e03-a04ce33f83c3
> Aug  9 14:31:45 pns-xen07 SM: [29979] Calling _map_VHD
> Aug  9 14:31:45 pns-xen07 SM: [29979] Calling ceph_plugin
> Aug  9 14:31:45 pns-xen07 SM: [29979] Calling rbd/nbd map on host OpaqueRef:0e9c18cb-c243-2d9e-b4db-7bb854e066df
> Aug  9 14:31:45 pns-xen07 SM: [29979] Raising exception [46, The VDI is not available [opterr=Could not find: /run/sr-mount/ff12160f-ff09-40bb-a874-1366ad907f44/VHD-4ad1754e-701f-4403-8e03-a04ce33f83c3]]
> Aug  9 14:31:45 pns-xen07 SM: [29979] Exception in activate/attach
> Aug  9 14:31:45 pns-xen07 SM: [29979] Removed host key host_OpaqueRef:0e9c18cb-c243-2d9e-b4db-7bb854e066df for 4ad1754e-701f-4403-8e03-a04ce33f83c3
> Aug  9 14:31:45 pns-xen07 SM: [29979] ****\* BLKTAP2:<function _activate_locked at 0x14b6668>: EXCEPTION <class 'SR.SROSError'>, The VDI is not available [opterr=Could not find: /run/sr-mount/ff12160f-ff09-40bb-a874-1366ad907f44/VHD-4ad1754e-701f-4403-8e03-a04ce33f83c3]
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 86, in wrapper
> Aug  9 14:31:45 pns-xen07 SM: [29979]     ret = op(self, *args)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1593, in _activate_locked
> Aug  9 14:31:45 pns-xen07 SM: [29979]     self._attach(sr_uuid, vdi_uuid)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1658, in _attach
> Aug  9 14:31:45 pns-xen07 SM: [29979]     attach_info = xmlrpclib.loads(self.target.attach(sr_uuid, vdi_uuid))[0][0]
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1115, in attach
> Aug  9 14:31:45 pns-xen07 SM: [29979]     return self.vdi.attach(sr_uuid, vdi_uuid)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/RBDSR.py", line 388, in attach
> Aug  9 14:31:45 pns-xen07 SM: [29979]     raise xs_errors.XenError('VDIUnavailable', opterr='Could not find: %s' % self.path)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/xs_errors.py", line 52, in __init__
> Aug  9 14:31:45 pns-xen07 SM: [29979]     raise SR.SROSError(errorcode, errormessage)
> Aug  9 14:31:45 pns-xen07 SM: [29979]
> Aug  9 14:31:45 pns-xen07 SM: [29979] lock: released /var/lock/sm/4ad1754e-701f-4403-8e03-a04ce33f83c3/vdi
> Aug  9 14:31:45 pns-xen07 SM: [29979] ****\* generic exception: vdi_activate: EXCEPTION <class 'SR.SROSError'>, The VDI is not available [opterr=Could not find: /run/sr-mount/ff12160f-ff09-40bb-a874-1366ad907f44/VHD-4ad1754e-701f-4403-8e03-a04ce33f83c3]
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/SRCommand.py", line 110, in run
> Aug  9 14:31:45 pns-xen07 SM: [29979]     return self._run_locked(sr)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/SRCommand.py", line 159, in _run_locked
> Aug  9 14:31:45 pns-xen07 SM: [29979]     rv = self._run(sr, target)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/SRCommand.py", line 264, in _run
> Aug  9 14:31:45 pns-xen07 SM: [29979]     writable, caching_params)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1560, in activate
> Aug  9 14:31:45 pns-xen07 SM: [29979]     if self._activate_locked(sr_uuid, vdi_uuid, options):
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 86, in wrapper
> Aug  9 14:31:45 pns-xen07 SM: [29979]     ret = op(self, *args)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1593, in _activate_locked
> Aug  9 14:31:45 pns-xen07 SM: [29979]     self._attach(sr_uuid, vdi_uuid)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1658, in _attach
> Aug  9 14:31:45 pns-xen07 SM: [29979]     attach_info = xmlrpclib.loads(self.target.attach(sr_uuid, vdi_uuid))[0][0]
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1115, in attach
> Aug  9 14:31:45 pns-xen07 SM: [29979]     return self.vdi.attach(sr_uuid, vdi_uuid)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/RBDSR.py", line 388, in attach
> Aug  9 14:31:45 pns-xen07 SM: [29979]     raise xs_errors.XenError('VDIUnavailable', opterr='Could not find: %s' % self.path)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/xs_errors.py", line 52, in __init__
> Aug  9 14:31:45 pns-xen07 SM: [29979]     raise SR.SROSError(errorcode, errormessage)
> Aug  9 14:31:45 pns-xen07 SM: [29979]
> Aug  9 14:31:45 pns-xen07 SM: [29979] ****\* RBD: EXCEPTION <class 'SR.SROSError'>, The VDI is not available [opterr=Could not find: /run/sr-mount/ff12160f-ff09-40bb-a874-1366ad907f44/VHD-4ad1754e-701f-4403-8e03-a04ce33f83c3]
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/SRCommand.py", line 352, in run
> Aug  9 14:31:45 pns-xen07 SM: [29979]     ret = cmd.run(sr)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/SRCommand.py", line 110, in run
> Aug  9 14:31:45 pns-xen07 SM: [29979]     return self._run_locked(sr)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/SRCommand.py", line 159, in _run_locked
> Aug  9 14:31:45 pns-xen07 SM: [29979]     rv = self._run(sr, target)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/SRCommand.py", line 264, in _run
> Aug  9 14:31:45 pns-xen07 SM: [29979]     writable, caching_params)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1560, in activate
> Aug  9 14:31:45 pns-xen07 SM: [29979]     if self._activate_locked(sr_uuid, vdi_uuid, options):
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 86, in wrapper
> Aug  9 14:31:45 pns-xen07 SM: [29979]     ret = op(self, *args)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1593, in _activate_locked
> Aug  9 14:31:45 pns-xen07 SM: [29979]     self._attach(sr_uuid, vdi_uuid)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1658, in _attach
> Aug  9 14:31:45 pns-xen07 SM: [29979]     attach_info = xmlrpclib.loads(self.target.attach(sr_uuid, vdi_uuid))[0][0]
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/blktap2.py", line 1115, in attach
> Aug  9 14:31:45 pns-xen07 SM: [29979]     return self.vdi.attach(sr_uuid, vdi_uuid)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/RBDSR.py", line 388, in attach
> Aug  9 14:31:45 pns-xen07 SM: [29979]     raise xs_errors.XenError('VDIUnavailable', opterr='Could not find: %s' % self.path)
> Aug  9 14:31:45 pns-xen07 SM: [29979]   File "/opt/xensource/sm/xs_errors.py", line 52, in __init__
> Aug  9 14:31:45 pns-xen07 SM: [29979]     raise SR.SROSError(errorcode, errormessage)
> Aug  9 14:31:45 pns-xen07 SM: [29979] 

Unfortunately this renders backup solutions relying on any kind of export (e.g. XenOrchestra) useless

**Comment by Emmenemoi** [comment]
It looks like your using fuse.
Does the problem persists using nbd?

**Comment by mhoffmann75** [comment]
D'oh, could have been the wrong log due to switching often between nbd and fuse when encountering bugs in nbd mode :-)

But anyway same problem with nbd mode:

> Aug  9 15:54:48 pns-xen07 SM: [15684] vdi_activate {'sr_uuid': 'ff12160f-ff09-40bb-a874-1366ad907f44', 'subtask_of': 'DummyRef:|a10e6d1a-f689-a071-f8f2-77997ef22621|VDI.activate', 'vdi_ref': 'OpaqueRef:6f21a903-824c-d902-de9f-9c0d052f98b0', 'vdi_on_boot': 'persist', 'args': ['false'], 'vdi_location': '9a076c42-70b5-4aeb-a7c6-a11b7372e8fc', 'host_ref': 'OpaqueRef:0e9c18cb-c243-2d9e-b4db-7bb854e066df', 'session_ref': 'OpaqueRef:780deb13-c20e-406b-ceb2-93a512af4ca8', 'device_config': {'SRmaster': 'true'}, 'command': 'vdi_activate', 'vdi_allow_caching': 'false', 'sr_ref': 'OpaqueRef:5a051e6e-4e23-beff-e3c7-7f7c926575fc', 'vdi_uuid': '9a076c42-70b5-4aeb-a7c6-a11b7372e8fc'}
> Aug  9 15:54:48 pns-xen07 SM: [15684] lock: opening lock file /var/lock/sm/9a076c42-70b5-4aeb-a7c6-a11b7372e8fc/vdi
> Aug  9 15:54:48 pns-xen07 SM: [15684] blktap2.activate
> Aug  9 15:54:48 pns-xen07 SM: [15684] lock: acquired /var/lock/sm/9a076c42-70b5-4aeb-a7c6-a11b7372e8fc/vdi
> Aug  9 15:54:48 pns-xen07 SM: [15684] Adding tag to: 9a076c42-70b5-4aeb-a7c6-a11b7372e8fc
> Aug  9 15:54:48 pns-xen07 SM: [15684] Activate lock succeeded
> Aug  9 15:54:48 pns-xen07 SM: [15684] ['ceph', 'df', '--format', 'json', '--name', 'client.admin']
> Aug  9 15:54:48 pns-xen07 SM: [15684]   preit SUCCESS
> Aug  9 15:54:48 pns-xen07 SM: [15684] RBDVDI.attach for 9a076c42-70b5-4aeb-a7c6-a11b7372e8fc
> Aug  9 15:54:48 pns-xen07 SM: [15684] Calling _map_VHD
> Aug  9 15:54:48 pns-xen07 SM: [15684] Calling ceph_plugin
> Aug  9 15:54:48 pns-xen07 SM: [15684] Calling rbd/nbd map on host OpaqueRef:0e9c18cb-c243-2d9e-b4db-7bb854e066df
> Aug  9 15:54:48 pns-xen07 SM: [15766] ['rbd-nbd', '--nbds_max', '64', 'map', 'RBD_XenStorage-ff12160f-ff09-40bb-a874-1366ad907f44/VHD-9a076c42-70b5-4aeb-a7c6-a11b7372e8fc', '--name', 'client.admin']
> Aug  9 15:54:48 pns-xen07 SM: [15766] FAILED in util.pread: (rc 1) stdout: '', stderr: 'rbd-nbd: failed to map, status: (2) No such file or directory
> Aug  9 15:54:48 pns-xen07 SM: [15766] 2016-08-09 15:54:48.794206 7f679014ae00 -1 asok(0x7f679aadb660) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-client.admin.asok': (17) File exists
> Aug  9 15:54:48 pns-xen07 SM: [15766] '
> Aug  9 15:54:48 pns-xen07 SM: [15684] Exception in activate/attach
> Aug  9 15:54:48 pns-xen07 SM: [15684] Removed host key host_OpaqueRef:0e9c18cb-c243-2d9e-b4db-7bb854e066df for 9a076c42-70b5-4aeb-a7c6-a11b7372e8fc
> Aug  9 15:54:48 pns-xen07 SM: [15684] ****\* BLKTAP2:<function _activate_locked at 0x25725f0>: EXCEPTION <class 'XenAPI.Failure'>, ['XENAPI_PLUGIN_FAILURE', 'map', 'CommandException', 'Operation not permitted']
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/blktap2.py", line 86, in wrapper
> Aug  9 15:54:48 pns-xen07 SM: [15684]     ret = op(self, *args)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/blktap2.py", line 1593, in _activate_locked
> Aug  9 15:54:48 pns-xen07 SM: [15684]     self._attach(sr_uuid, vdi_uuid)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/blktap2.py", line 1658, in _attach
> Aug  9 15:54:48 pns-xen07 SM: [15684]     attach_info = xmlrpclib.loads(self.target.attach(sr_uuid, vdi_uuid))[0][0]
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/blktap2.py", line 1115, in attach
> Aug  9 15:54:48 pns-xen07 SM: [15684]     return self.vdi.attach(sr_uuid, vdi_uuid)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/RBDSR.py", line 385, in attach
> Aug  9 15:54:48 pns-xen07 SM: [15684]     self._map_VHD(vdi_uuid)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/cephutils.py", line 399, in _map_VHD
> Aug  9 15:54:48 pns-xen07 SM: [15684]     self._call_plugin('map',args)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/cephutils.py", line 372, in _call_plugin
> Aug  9 15:54:48 pns-xen07 SM: [15684]     if not self.session.xenapi.host.call_plugin(host_ref, "ceph_plugin", op, args):
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/usr/lib/python2.7/site-packages/XenAPI.py", line 248, in __call__
> Aug  9 15:54:48 pns-xen07 SM: [15684]     return self.**send(self.__name, args)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/usr/lib/python2.7/site-packages/XenAPI.py", line 150, in xenapi_request
> Aug  9 15:54:48 pns-xen07 SM: [15684]     result = _parse_result(getattr(self, methodname)(_full_params))
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/usr/lib/python2.7/site-packages/XenAPI.py", line 222, in _parse_result
> Aug  9 15:54:48 pns-xen07 SM: [15684]     raise Failure(result['ErrorDescription'])
> Aug  9 15:54:48 pns-xen07 SM: [15684]
> Aug  9 15:54:48 pns-xen07 SM: [15684] Raising exception [46, The VDI is not available [opterr=['XENAPI_PLUGIN_FAILURE', 'map', 'CommandException', 'Operation not permitted']]]
> Aug  9 15:54:48 pns-xen07 SM: [15684] lock: released /var/lock/sm/9a076c42-70b5-4aeb-a7c6-a11b7372e8fc/vdi
> Aug  9 15:54:48 pns-xen07 SM: [15684] *_**\* generic exception: vdi_activate: EXCEPTION <class 'SR.SROSError'>, The VDI is not available [opterr=['XENAPI_PLUGIN_FAILURE', 'map', 'CommandException', 'Operation not permitted']]
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/SRCommand.py", line 110, in run
> Aug  9 15:54:48 pns-xen07 SM: [15684]     return self._run_locked(sr)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/SRCommand.py", line 159, in _run_locked
> Aug  9 15:54:48 pns-xen07 SM: [15684]     rv = self._run(sr, target)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/SRCommand.py", line 264, in _run
> Aug  9 15:54:48 pns-xen07 SM: [15684]     writable, caching_params)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/blktap2.py", line 1560, in activate
> Aug  9 15:54:48 pns-xen07 SM: [15684]     if self._activate_locked(sr_uuid, vdi_uuid, options):
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/blktap2.py", line 94, in wrapper
> Aug  9 15:54:48 pns-xen07 SM: [15684]     raise xs_errors.XenError(excType, opterr=msg)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/xs_errors.py", line 52, in __init**
> Aug  9 15:54:48 pns-xen07 SM: [15684]     raise SR.SROSError(errorcode, errormessage)
> Aug  9 15:54:48 pns-xen07 SM: [15684]
> Aug  9 15:54:48 pns-xen07 SM: [15684] ****\* RBD: EXCEPTION <class 'SR.SROSError'>, The VDI is not available [opterr=['XENAPI_PLUGIN_FAILURE', 'map', 'CommandException', 'Operation not permitted']]
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/SRCommand.py", line 352, in run
> Aug  9 15:54:48 pns-xen07 SM: [15684]     ret = cmd.run(sr)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/SRCommand.py", line 110, in run
> Aug  9 15:54:48 pns-xen07 SM: [15684]     return self._run_locked(sr)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/SRCommand.py", line 159, in _run_locked
> Aug  9 15:54:48 pns-xen07 SM: [15684]     rv = self._run(sr, target)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/SRCommand.py", line 264, in _run
> Aug  9 15:54:48 pns-xen07 SM: [15684]     writable, caching_params)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/blktap2.py", line 1560, in activate
> Aug  9 15:54:48 pns-xen07 SM: [15684]     if self._activate_locked(sr_uuid, vdi_uuid, options):
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/blktap2.py", line 94, in wrapper
> Aug  9 15:54:48 pns-xen07 SM: [15684]     raise xs_errors.XenError(excType, opterr=msg)
> Aug  9 15:54:48 pns-xen07 SM: [15684]   File "/opt/xensource/sm/xs_errors.py", line 52, in __init__
> Aug  9 15:54:48 pns-xen07 SM: [15684]     raise SR.SROSError(errorcode, errormessage)
> Aug  9 15:54:48 pns-xen07 SM: [15684]
> Aug  9 15:54:48 pns-xen07 SM: [15684] lock: closed /var/lock/sm/9a076c42-70b5-4aeb-a7c6-a11b7372e8fc/vdi

**Comment by mhoffmann75** [comment]
Please Note that this export of snapshot like backup software does it

**Comment by mhoffmann75** [comment]
Just to clarify this. A VM not running can be exported via XenCenter without problems. But when VM is running i need to create a snapshot (from my understanding to create a stale disk). Then i try to export this snapshot via XenCenter. I guess this is the same way backups via XenOrchestra work. 
However it ends with this error:

> Aug 9 15:54:48 pns-xen07 SM: [15684] RBDVDI.attach for 9a076c42-70b5-4aeb-a7c6-a11b7372e8fc
> Aug 9 15:54:48 pns-xen07 SM: [15684] Calling map_VHD
> Aug 9 15:54:48 pns-xen07 SM: [15684] Calling ceph_plugin
> Aug 9 15:54:48 pns-xen07 SM: [15684] Calling rbd/nbd map on host OpaqueRef:0e9c18cb-c243-2d9e-b4db-7bb854e066df
> Aug 9 15:54:48 pns-xen07 SM: [15766] ['rbd-nbd', '--nbds_max', '64', 'map', 'RBD_XenStorage-ff12160f-ff09-40bb-a874-1366ad907f44/VHD-9a076c42-70b5-4aeb-a7c6-a11b7372e8fc', '--name', 'client.admin']
> Aug 9 15:54:48 pns-xen07 SM: [15766] FAILED in util.pread: (rc 1) stdout: '', stderr: 'rbd-nbd: failed to map, status: (2) No such file or directory

Please note, that 'rbd list --pool RBD_XenStorage-ff12160f-ff09-40bb-a874-1366ad907f44' does not list a disk **VHD-9a076c42-70b5-4aeb-a7c6-a11b7372e8fc** - so "No such file or directory" is true. Is this the disc from the snapshot?

I also deleted all my VMs and started from scratch setting up new VMs without cloning or stuff - but problem remains the same. Also double checked that it does use nbd mode this time :-)

Next i will give XenOrchestra another try but i'm afraid that it won't work since exporting of snapshots fails. 

Any idea? Should i provide more logs or information?

**Comment by rposudnevskiy** [comment]
Hi Martin,
Thank you for logs.
I'm working on this issue. I will let you know when I have some news.

**Comment by mhoffmann75** [comment]
Hi, okay thanks, let me know if i can be of any help. Just to complete the picture:
XenOrchestra Backup works as long as the VM is shutdown and **no snapshots** are involved. As soon as either the VM is running or using **XenOrchestra Delta Backup** snapshots come into play and backup fails. Interestingly XO backup on running VM says **success** (XO issue i guess), but backup is way too small and SMlog contains aforementioned errors...

**Comment by rposudnevskiy** [comment]
Hi Martin,
The Issue #11 has been fixed.
Please note that the export of snapshot is not supported in FUSE mode.

**Comment by mhoffmann75** [comment]
Works great. Thank you!
Export of Snapshots via XenCenter works and even XenOrchestra Backup of running VMs works. However DeltaBackup Mode (full on first backup, after that incremental backups) still fails. Unfortunately no errors in SMlog.
I will open another issue and provide logs.
